/* Generated By:JavaCC: Do not edit this line. SQLParserConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface SQLParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int PLUS = 5;
  /** RegularExpression Id. */
  int MINUS = 6;
  /** RegularExpression Id. */
  int MULTIPLY = 7;
  /** RegularExpression Id. */
  int DIVIDE = 8;
  /** RegularExpression Id. */
  int SEMICOLON = 9;
  /** RegularExpression Id. */
  int CREATE = 10;
  /** RegularExpression Id. */
  int VIEW = 11;
  /** RegularExpression Id. */
  int AS = 12;
  /** RegularExpression Id. */
  int SELECT = 13;
  /** RegularExpression Id. */
  int FROM = 14;
  /** RegularExpression Id. */
  int WITH = 15;
  /** RegularExpression Id. */
  int CASCADED = 16;
  /** RegularExpression Id. */
  int LOCAL = 17;
  /** RegularExpression Id. */
  int CHECK = 18;
  /** RegularExpression Id. */
  int OPTION = 19;
  /** RegularExpression Id. */
  int Id = 20;
  /** RegularExpression Id. */
  int CONSTANT = 21;
  /** RegularExpression Id. */
  int DIGIT = 22;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\";\"",
    "\"create\"",
    "\"view\"",
    "\"as\"",
    "\"select\"",
    "\"from\"",
    "\"with\"",
    "\"cascaded\"",
    "\"local\"",
    "\"check\"",
    "\"option\"",
    "<Id>",
    "<CONSTANT>",
    "<DIGIT>",
    "\"(\"",
    "\")\"",
    "\",\"",
  };

}
